### ISSUE TITLE
how to autocomplete snippet from Shougo/neosnippet-snippets

### ISSUE THREAD

**Issue by chenjie199234** [thomasfaingnaert/vim-lsp-neosnippet#5]
it seems that this plugin can only complete the snippets from the language server
how to complete the snippets from local plugin
like Shougo/neosnippet-snippets
or vim-snippets

**Comment by thomasfaingnaert** [comment]
> it seems that this plugin can only complete the snippets from the language server

Yes, its purpose is just to integrate `vim-lsp` and `neosnippet.vim`.

> how to complete the snippets from local plugin
> like Shougo/neosnippet-snippets
> or vim-snippets

Please refer to the documentation of neosnippet.vim on how to configure it to read your own snippets.
